version: 0.0
os: linux
file_exists_behavior: OVERWRITE 

files:
  - source: .
    destination: /var/www/madhurbazar

hooks:
  BeforeInstall:  
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: root
