version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - echo "Moving to backend folder..."
      - cd madhurbazarbackend || exit 1
      - echo "Installing dependencies..."
      - npm install || exit 1

  build:
    commands:
      - echo "Skipping build step (backend project)"

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
